Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2021-08, with the labels that each got.

#344 Task - Footer
  admin/package.json
  admin/public/images/logo_canada.png
  admin/resources/css/app.css
  admin/resources/js/components/Footer.tsx
  admin/resources/js/components/dashboard/Dashboard.tsx
Labels: feature

#325 Dashboard UI Rework
  .gitattributes
  README.md
  admin/.gitignore
  admin/hydrogen.config.json
  admin/package-lock.json
  admin/resources/css/hydrogen.css
  admin/resources/js/components/H2Components/InputContext.tsx
  admin/resources/js/components/H2Components/InputError.tsx
  admin/resources/js/components/H2Components/Pill.tsx
  admin/resources/js/components/PoolDashboard.tsx
  admin/resources/js/components/Table.tsx
  admin/resources/js/components/classification/ClassificationPage.tsx
  admin/resources/js/components/classification/ClassificationTable.tsx
  admin/resources/js/components/cmoAsset/CmoAssetPage.tsx
  admin/resources/js/components/cmoAsset/CmoAssetTable.tsx
  admin/resources/js/components/dashboard/Dashboard.tsx
  admin/resources/js/components/form/Form.tsx
  admin/resources/js/components/menu/SideMenu.tsx
  admin/resources/js/components/operationalRequirement/OperationalRequirementPage.tsx
  admin/resources/js/components/operationalRequirement/OperationalRequirementTable.tsx
  admin/resources/js/components/pool/PoolPage.tsx
  admin/resources/js/components/poolCandidate/PoolCandidatePage.tsx
  admin/resources/js/components/user/UserPage.tsx
  admin/resources/js/components/user/UserTable.tsx
  api/composer.lock
Labels: design

#390 Bugfix - Admin Pool Dashboard pools query
  admin/resources/css/hydrogen.css
  admin/resources/js/components/PoolDashboard.tsx
  admin/resources/js/components/dashboard/Dashboard.tsx
  admin/resources/js/stories/Pool.stories.tsx
Labels: bug
