Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2021-11, with the labels that each got.

#928 Feature - request page
  admin/resources/css/hydrogen.css
  admin/resources/js/api/generated.ts
  admin/resources/js/stories/Department.stories.tsx
  api/graphql/schema.graphql
  api/storage/app/lighthouse-schema.graphql
  common/src/api/generated.ts
  common/src/components/form/Select/Select.tsx
  talentsearch/resources/css/app.css
  talentsearch/resources/css/hydrogen.css
  talentsearch/resources/js/api/generated.ts
  talentsearch/resources/js/api/poolCandidateSearchOperations.graphql
  talentsearch/resources/js/components/PageContainer.tsx
  talentsearch/resources/js/components/Router.tsx
  talentsearch/resources/js/components/request/CreateRequest.tsx
  talentsearch/resources/js/components/request/RequestPage.tsx
  talentsearch/resources/js/components/request/SummaryOfFilters.tsx
  talentsearch/resources/js/components/search/EstimatedCandidates.tsx
  talentsearch/resources/js/components/search/SearchForm.tsx
  talentsearch/resources/js/components/search/SearchPage.tsx
  talentsearch/resources/js/stories/Pages.stories.tsx
  talentsearch/resources/js/stories/RequestForm.stories.tsx
  talentsearch/resources/js/stories/SearchForm.stories.tsx
  talentsearch/resources/js/talentSearchRoutes.ts
Labels: feature

#972 Feature - search request table
  admin/resources/css/hydrogen.css
  admin/resources/js/adminRoutes.ts
  admin/resources/js/api/generated.ts
  admin/resources/js/api/poolCandidateSearchRequestOperations.graphql
  admin/resources/js/components/PoolDashboard.tsx
  admin/resources/js/components/searchRequest/SearchRequestPage.tsx
  admin/resources/js/components/searchRequest/SearchRequestTable.tsx
  admin/resources/js/stories/SearchRequest.stories.tsx
  common/package-lock.json
  common/src/api/generated.ts
  common/src/fakeData/fakeSearchRequests.ts
  common/src/fakeData/index.ts
Labels: feature

#1131 increase Dependebot open PR limit to 15
  .github/dependabot.yml
Labels: Tooling

#1144 turn off function-component-definition rule
  admin/.eslintrc
  common/.eslintrc
  talentsearch/.eslintrc
Labels: Tooling

#1187 Debt - ignore generated files
  admin/.gitignore
  admin/resources/css/.gitignore
  admin/resources/css/hydrogen.css
  admin/resources/js/api/.gitignore
  admin/resources/js/api/generated.ts
  admin/resources/js/lang/en.json
  admin/resources/js/lang/untranslated.json
  api/app/GraphQL/Scalars/KeyString.php
  api/storage/app/.gitignore
  api/storage/app/lighthouse-schema.graphql
  common/.gitignore
  common/src/api/.gitignore
  common/src/api/generated.ts
  common/src/components/NotFound/NotFound.stories.tsx
  common/src/components/NotFound/NotFound.tsx
  common/src/css/.gitignore
  talentsearch/resources/css/.gitignore
  talentsearch/resources/css/hydrogen.css
  talentsearch/resources/js/api/.gitignore
  talentsearch/resources/js/api/generated.ts
Labels: debt

#1148 Feature - search form api
  admin/hydrogen.config.json
  api/app/Policies/ClassificationPolicy.php
  api/app/Policies/CmoAssetPolicy.php
  api/app/Policies/DepartmentPolicy.php
  api/app/Policies/OperationalRequirementPolicy.php
  api/graphql/schema.graphql
  talentsearch/resources/js/api/poolCandidateFilterOperations.graphql
  talentsearch/resources/js/components/search/SearchForm.tsx
  talentsearch/resources/js/components/search/SearchPage.tsx
  talentsearch/resources/js/stories/SearchForm.stories.tsx
Labels: feature

#1198 Feature - store and fetch filter data on history state
  admin/resources/js/components/PoolDashboard.tsx
  admin/webpack.mix.js
  common/package-lock.json
  common/package.json
  common/src/components/SearchRequestFilters/SearchRequestFilters.tsx
  common/src/components/Toast/Toast.tsx
  common/src/components/Toast/index.ts
  common/src/components/index.ts
  common/src/helpers/router.tsx
  talentsearch/resources/css/app.css
  talentsearch/resources/js/api/poolCandidateFilterOperations.graphql
  talentsearch/resources/js/components/PageContainer.tsx
  talentsearch/resources/js/components/Router.tsx
  talentsearch/resources/js/components/request/CreateRequest.tsx
  talentsearch/resources/js/components/request/RequestPage.tsx
  talentsearch/resources/js/components/search/SearchForm.tsx
  talentsearch/resources/js/components/search/SearchPage.tsx
  talentsearch/resources/js/helpers/localize.ts
  talentsearch/resources/js/helpers/router.tsx
  talentsearch/resources/js/helpers/util.ts
  talentsearch/resources/js/stories/SearchForm.stories.tsx
  talentsearch/webpack.mix.js
Labels: feature
