Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2021-09, with the labels that each got.

#487 API - Create department model
  api/app/Models/Department.php
  api/database/migrations/2021_09_13_180950_create_departments_table.php
  api/database/seeders/DatabaseSeeder.php
  api/database/seeders/DepartmentSeeder.php
  api/graphql/schema.graphql
Labels: feature

#493 Department graphql operations
  admin/resources/js/api/departmentOperations.graphql
  admin/resources/js/api/generated.ts
Labels: feature

#494 Dashboard - Department table
  admin/resources/js/components/PoolDashboard.tsx
  admin/resources/js/components/department/DepartmentPage.tsx
  admin/resources/js/components/department/DepartmentTable.tsx
  admin/resources/js/fakeData/fakeDepartments.ts
  admin/resources/js/helpers/routes.ts
  admin/resources/js/stories/Department.stories.tsx
Labels: feature

#495 Dashboard - Department create update forms
  admin/resources/js/components/PoolDashboard.tsx
  admin/resources/js/components/department/CreateDepartment.tsx
  admin/resources/js/components/department/UpdateDepartment.tsx
  admin/resources/js/components/department/messages.ts
  admin/resources/js/stories/Department.stories.tsx
Labels: feature

#498 API - query to get number of pool candidates with filters
  api/app/GraphQL/Operators/PostgreSQLOperator.php
  api/app/Providers/GraphQLServiceProvider.php
  api/bootstrap/app.php
  api/graphql/schema.graphql
Labels: feature

#509 Update departments table id column type to uuid
  api/database/migrations/2021_09_13_180950_create_departments_table.php
Labels: bug

#508 Fix Table Component Toggle All
  admin/resources/js/components/Table.tsx
Labels: bug

#530 API - Change id reference column types from string to uuid
  api/database/migrations/2021_05_05_163948_create_users_table.php
  api/database/migrations/2021_05_26_195131_create_pools_table.php
  api/database/migrations/2021_05_27_182801_create_classifications_table.php
  api/database/migrations/2021_05_27_182844_create_operational_requirements_table.php
  api/database/migrations/2021_05_28_200606_create_pool_lookup_pivot_tables.php
  api/database/migrations/2021_06_01_140524_create_pool_candidates_table.php
  api/database/migrations/2021_09_13_180950_create_departments_table.php
Labels: bug

#549 Update fakeData and Storybook stories
  admin/package-lock.json
  admin/resources/js/components/cmoAsset/CmoAssetTable.tsx
  admin/resources/js/components/operationalRequirement/OperationalRequirementTable.tsx
  admin/resources/js/fakeData/fakeClassifications.ts
  admin/resources/js/fakeData/fakeCmoAssets.ts
  admin/resources/js/fakeData/fakeDepartments.ts
  admin/resources/js/fakeData/fakeOperationalRequirements.ts
  admin/resources/js/fakeData/fakePoolCandidates.ts
  admin/resources/js/fakeData/fakePools.ts
  admin/resources/js/fakeData/fakeUsers.ts
  admin/resources/js/stories/Classification.stories.tsx
  admin/resources/js/stories/CmoAsset.stories.tsx
  admin/resources/js/stories/Department.stories.tsx
  admin/resources/js/stories/OperationalRequirement.stories.tsx
  admin/resources/js/stories/Pool.stories.tsx
  admin/resources/js/stories/PoolCandidate.stories.tsx
  admin/resources/js/stories/User.stories.tsx
  api/app/Models/Department.php
  common/package-lock.json
  talentsearch/package-lock.json
Labels: bug, debt

#536 Minor Table and Form UI Updates
  admin/package-lock.json
  admin/resources/css/hydrogen.css
  admin/resources/js/components/Footer.tsx
  admin/resources/js/components/Table.tsx
  admin/resources/js/components/classification/CreateClassification.tsx
  admin/resources/js/components/classification/UpdateClassification.tsx
  admin/resources/js/components/cmoAsset/CreateCmoAsset.tsx
  admin/resources/js/components/cmoAsset/UpdateCmoAsset.tsx
  admin/resources/js/components/dashboard/Dashboard.tsx
  admin/resources/js/components/department/CreateDepartment.tsx
  admin/resources/js/components/department/UpdateDepartment.tsx
  admin/resources/js/components/menu/SideMenu.tsx
  admin/resources/js/components/operationalRequirement/CreateOperationalRequirement.tsx
  admin/resources/js/components/operationalRequirement/UpdateOperationalRequirement.tsx
  admin/resources/js/components/pool/CreatePool.tsx
  admin/resources/js/components/pool/PoolTable.tsx
  admin/resources/js/components/pool/UpdatePool.tsx
  admin/resources/js/components/poolCandidate/CreatePoolCandidate.tsx
  admin/resources/js/components/poolCandidate/UpdatePoolCandidate.tsx
  admin/resources/js/components/user/CreateUser.tsx
  admin/resources/js/components/user/UpdateUser.tsx
  auth/package-lock.json
  common/src/components/form/MultiSelect/MultiSelect.tsx
  common/src/components/form/Submit/Submit.tsx
Labels: bug, debt, design

#511 API - Add candidate search requests and pool candidate filters to api
  api/app/Models/Department.php
  api/app/Models/PoolCandidateFilter.php
  api/app/Models/PoolCandidateSearchRequest.php
  api/database/factories/PoolCandidateFilterFactory.php
  api/database/factories/PoolCandidateSearchRequestFactory.php
  api/database/migrations/2021_09_17_135548_create_pool_candidate_search_requests_table.php
  api/database/migrations/2021_09_17_190139_create_pool_candidate_filters_table.php
  api/database/seeders/DatabaseSeeder.php
  api/graphql/schema.graphql
Labels: feature
