Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2021-07, with the labels that each got.

#240 Task - Styling Input and Textarea
  admin/resources/js/components/H2Components/Fieldset.tsx
  admin/resources/js/components/H2Components/InputContext.tsx
  admin/resources/js/components/H2Components/InputError.tsx
  admin/resources/js/components/H2Components/InputLabel.tsx
  admin/resources/js/components/H2Components/InputWrapper.tsx
  admin/resources/js/components/form/Checkbox.tsx
  admin/resources/js/components/form/Checklist.tsx
  admin/resources/js/components/form/Input.tsx
  admin/resources/js/components/form/TextArea.tsx
  admin/resources/js/stories/Input.stories.tsx
  admin/resources/js/stories/TextArea.stories.tsx
Labels: feature

#270 Task - Update gitignore in auth service folder
  auth/.gitignore
  auth/package-lock.json
Labels: debt

#269 Bugfix - Storybook stories deprecated warning
  admin/resources/js/stories/H2Components/Button.stories.tsx
  admin/resources/js/stories/form/Input.stories.tsx
  admin/resources/js/stories/form/TextArea.stories.tsx
Labels: bug

#256 Feature - Create and update classification
  admin/resources/js/api/classificationOperations.graphql
  admin/resources/js/api/generated.ts
  admin/resources/js/components/PoolDashboard.tsx
  admin/resources/js/components/classification/ClassificationPage.tsx
  admin/resources/js/components/classification/ClassificationTable.tsx
  admin/resources/js/components/classification/CreateClassification.tsx
  admin/resources/js/components/classification/UpdateClassification.tsx
  admin/resources/js/components/form/Input.tsx
  admin/resources/js/components/form/errorMessages.ts
  admin/resources/js/model/localizedConstants.tsx
  admin/resources/js/stories/Classification.stories.tsx
  admin/resources/js/stories/ClassificationTable.stories.tsx
  api/graphql/schema.graphql
Labels: feature
