Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2022-09, with the labels that each got.

#3567 migrate data from PoolCandidate to User
  api/database/migrations/2022_08_02_193722_poolcandidate_data_to_user.php
Labels: deployment

#3866 Import talentsearch french strings into merged Storybook (hosted on Chromatic)
  frontend/admin/.storybook/preview.js
  frontend/indigenousapprenticeship/src/js/components/Home/Home.stories.tsx
Labels: bug

#3942 Update straggler LoginIcon after @heroicon update
  frontend/common/src/components/SideMenu/SideMenu.stories.tsx
Labels: bug

#3965 add missing dependencies in lockfile
  frontend/package-lock.json
Labels: interruption

#4103 Bug - Improve unique email validation
  api/app/GraphQL/Validators/UpdateUserInputValidator.php
  api/graphql/schema.graphql
  api/storage/app/lighthouse-schema.graphql
  frontend/admin/src/js/api/userOperations.graphql
  frontend/admin/src/js/components/user/CreateUser.tsx
  frontend/admin/src/js/components/user/UpdateUser.tsx
  frontend/talentsearch/src/js/components/GovernmentInfoForm/GovInfoFormOperations.graphql
  frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.tsx
  frontend/talentsearch/src/js/components/aboutMeForm/aboutMeFormOperations.graphql
  frontend/talentsearch/src/js/components/createAccount/CreateAccountPage.tsx
  frontend/talentsearch/src/js/components/createAccount/createAccountOperations.graphql
  frontend/talentsearch/src/js/components/employmentEquityForm/EmploymentEquityForm.test.tsx
  frontend/talentsearch/src/js/components/employmentEquityForm/employmentEquityOperations.graphql
  frontend/talentsearch/src/js/components/languageInformationForm/LanguageInformationForm.stories.tsx
  frontend/talentsearch/src/js/components/languageInformationForm/LanguageInformationOperations.graphql
  frontend/talentsearch/src/js/components/myStatusForm/myStatusOperations.graphql
  frontend/talentsearch/src/js/components/roleSalaryForm/RoleSalaryFormOperations.graphql
  frontend/talentsearch/src/js/components/workLocationPreferenceForm/workLocationPreferenceOperations.graphql
  frontend/talentsearch/src/js/components/workPreferencesForm/workPreferenceOperations.graphql
Labels: bug

#4108 Disable docker layer caching in github action
  .github/workflows/e2e-tests.yml
Labels: bug
