Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2022-02, with the labels that each got.

#1964 Add missing storybook update to lock file
  frontend/package-lock.json
Labels: dependencies, interruption

#1966 Feature/1534 accordion component - version 2
  frontend/common/src/components/accordion/Accordion.stories.tsx
  frontend/common/src/components/accordion/Accordion.tsx
  frontend/common/src/components/accordion/index.ts
Labels: feature

#1955 Feature - pagination component
  .vscode/project-words.txt
  frontend/common/CssStub.js
  frontend/common/jest.config.js
  frontend/common/package.json
  frontend/common/src/components/Button/Button.tsx
  frontend/common/src/components/Pagination/Pagination.stories.tsx
  frontend/common/src/components/Pagination/Pagination.test.tsx
  frontend/common/src/components/Pagination/Pagination.tsx
  frontend/common/src/components/Pagination/index.ts
  frontend/common/src/components/Pagination/usePagination.ts
  frontend/common/src/css/common.css
  frontend/package-lock.json
  frontend/talentsearch/jest.config.js
  frontend/talentsearch/resources/js/tests/config/CssStub.js
Labels: feature

#1992 Bugfix - Quick fix search page heading layout
  frontend/talentsearch/resources/js/components/search/SearchHeading.tsx
Labels: bug

#2031 Request Login Locale
  frontend/admin/app/Http/Controllers/AuthController.php
  frontend/admin/resources/js/components/dashboard/Dashboard.tsx
Labels: interruption

#2038 Fix Jest dependencies
  frontend/common/package.json
  frontend/package-lock.json
Labels: interruption

#2035 1792 - add work experience form
  frontend/talentsearch/resources/js/components/workExperienceForm/WorkExperienceForm.stories.tsx
  frontend/talentsearch/resources/js/components/workExperienceForm/WorkExperienceForm.tsx
Labels: feature

#2087 Add sort options for eduction experience form
  frontend/talentsearch/resources/js/components/awardDetailsForm/AwardDetailsForm.tsx
  frontend/talentsearch/resources/js/components/educationExperienceForm/EducationExperienceForm.tsx
Labels: interruption

#2128 Default storybook viewer background to off-white
  frontend/admin/.storybook/preview.js
  frontend/common/.storybook/preview.js
  frontend/talentsearch/.storybook/preview.js
Labels: tooling, design

#2150 Checkbox with bounding box
  frontend/common/src/components/form/Checkbox/Checkbox.stories.tsx
  frontend/common/src/components/form/Checkbox/Checkbox.tsx
  frontend/common/src/components/form/Checklist/Checklist.tsx
  frontend/common/src/components/form/Radio/Radio.tsx
  frontend/common/src/components/form/RadioGroup/RadioGroup.tsx
  frontend/common/src/components/inputPartials/InputWrapper/InputWrapper.tsx
Labels: feature
