Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2022-08, with the labels that each got.

#3564 Citizen and Veteran backend
  api/app/Models/User.php
  api/database/factories/UserFactory.php
  api/database/helpers/ApiEnums.php
  api/database/migrations/2022_08_02_175856_add_citizen_veteran_fields.php
  api/graphql/schema.graphql
  api/storage/app/lighthouse-schema.graphql
  api/tests/Feature/UserTest.php
  frontend/common/src/fakeData/fakeUsers.ts
Labels: deployment

#3566 Update htaccess deployment
  infrastructure/conf/deploy.htaccess
  infrastructure/deploy.sh
  infrastructure/php-container/src/.htaccess
Labels: deployment

#3570 2834 azure yaml pipeline
  infrastructure/azure-pipelines.noop.yml
  infrastructure/azure-pipelines.yml
  infrastructure/bin/deploy.sh
  infrastructure/bin/set_php_versions.sh
  infrastructure/conf/deploy.htaccess
  infrastructure/deploy.sh
Labels: deployment

#3610 Bug - Revert storybook/react
  frontend/admin/package.json
  frontend/common/package.json
  frontend/indigenousapprenticeship/package.json
  frontend/talentsearch/package.json
Labels: bug, tooling, interruption

#3630 Bug - Fix Dep Updates
  frontend/admin/package.json
  frontend/common/package.json
  frontend/common/src/components/form/Select/SelectFieldV2.test.tsx
  frontend/common/src/components/form/Select/SelectFieldV2.tsx
  frontend/common/src/fakeData/fakeExperiences.ts
  frontend/common/src/messages/errorMessages.ts
  frontend/indigenousapprenticeship/package.json
  frontend/package-lock.json
  frontend/talentsearch/package.json
Labels: bug, dependencies, debt

#3644 Bug - 3580 - Fix Pool Validation
  api/app/GraphQL/Validators/Mutation/PublishPoolAdvertisementValidator.php
  api/app/Models/Pool.php
  api/database/factories/PoolFactory.php
  api/database/migrations/2022_08_09_164050_add_is_remote_column_pools_table.php
  api/graphql/schema.graphql
  api/storage/app/lighthouse-schema.graphql
  frontend/admin/src/js/components/pool/EditPool/OtherRequirementsSection.tsx
  frontend/admin/src/js/components/pool/EditPool/editPoolOperations.graphql
  frontend/admin/src/js/components/pool/ViewPool.tsx
  frontend/admin/src/js/components/pool/poolOperations.graphql
  frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx
  frontend/talentsearch/src/js/components/pool/poolOperations.graphql
Labels: deployment

#3614 Post deployment script
  infrastructure/bin/post_deployment.sh
Labels: deployment

#3735 Fix Dependabot auto-label GitHub workflow
  .github/workflows/dependabot-auto-label.yml
Labels: bug, tooling, interruption

#3757 Add leading zero to classification label
  frontend/admin/src/js/components/user/useFilterOptions.tsx
Labels: bug

#3763 Revert Hydrogen Overwrites
  frontend/admin/src/js/components/apiManagedTable/TableHeader.tsx
  frontend/common/src/components/Button/Button.tsx
Labels: bug

#3758 Fancy filter styling
  frontend/admin/src/js/components/user/UserTableFilterDialog.tsx
Labels: design

#3765 Updates EE dialog styles and content
  frontend/common/src/components/Dialog/Dialog.tsx
  frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/Definition.tsx
  frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/DisabilityDialog.tsx
  frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/IndigenousDialog.tsx
  frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/VisibleMinorityDialog.tsx
  frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/WomanDialog.tsx
Labels: design, copy

#3759 Updates the H2 package namespace
  frontend/admin/.storybook/main.js
  frontend/admin/package.json
  frontend/admin/webpack.base.js
  frontend/common/.storybook/main.js
  frontend/common/package.json
  frontend/hydrogen.config.json
  frontend/indigenousapprenticeship/.storybook/main.js
  frontend/indigenousapprenticeship/package.json
  frontend/indigenousapprenticeship/webpack.base.js
  frontend/package-lock.json
  frontend/talentsearch/.storybook/main.js
  frontend/talentsearch/package.json
  frontend/talentsearch/webpack.base.js
  maintenance/scripts/refresh_common.sh
Labels: dependencies
