Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2022-01, with the labels that each got.

#1645 Feature - Skills search bar
  common/src/components/form/Input/Input.tsx
  common/src/components/inputPartials/InputLabel/InputLabel.tsx
  common/src/components/inputPartials/InputWrapper/InputWrapper.tsx
  talentsearch/resources/js/components/skills/SearchBar.tsx
  talentsearch/resources/js/stories/SearchBar.stories.tsx
Labels: feature

#1687 Bugfix - talent search module resolution
  talentsearch/tsconfig.json
  talentsearch/webpack.mix.js
Labels: bug

#1770 Bugfix - Set use useForm type in CreateRequest component
  talentsearch/resources/js/components/request/CreateRequest.tsx
Labels: bug

#1772 Bugfix - Set 'Get in touch' link to a mailto with pool owners email
  talentsearch/resources/js/components/search/SearchContainer.tsx
Labels: bug

#1774 Manual dependency updates 2022-01-17
  admin/package-lock.json
  admin/package.json
  api/composer.lock
  auth/composer.lock
  common/package-lock.json
  common/package.json
  talentsearch/composer.lock
  talentsearch/package-lock.json
  talentsearch/package.json
Labels: dependencies

#1767 Feature - Skill results
  frontend/admin/hydrogen.config.json
  frontend/talentsearch/jest.config.js
  frontend/talentsearch/resources/js/components/skills/SkillResults.tsx
  frontend/talentsearch/resources/js/stories/skills/SearchBar.stories.tsx
  frontend/talentsearch/resources/js/stories/skills/SkillResults.stories.tsx
  frontend/talentsearch/resources/js/tests/config/CSSStub.js
  frontend/talentsearch/resources/js/tests/skills/SkillResults.test.tsx
Labels: feature

#1901 Bugfix - Remove duplicate moduleNameMappers in jest config
  frontend/talentsearch/jest.config.js
Labels: bug, interruption

#1959 Fix translation extract command
  frontend/admin/package.json
  frontend/common/package.json
  frontend/talentsearch/package.json
Labels: bug, tooling, interruption
