Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2022-04, with the labels that each got.

#2373 Fix failing tests on admin
  frontend/common/src/fakeData/fakeExperiences.ts
  frontend/talentsearch/src/js/components/skills/SkillAccordion/SkillAccordion.test.tsx
  frontend/talentsearch/src/js/components/skills/SkillAccordion/SkillAccordion.tsx
Labels: bug, interruption

#2315 Bashrc for script runs
  infrastructure/deploy.sh
  maintenance/scripts/lib/load_nvm.sh
  maintenance/scripts/refresh_admin.sh
  maintenance/scripts/refresh_auth.sh
  maintenance/scripts/refresh_common.sh
  maintenance/scripts/refresh_talentsearch.sh
  maintenance/scripts/setup.sh
Labels: PR:trivial

#2369 Fill in the profile form with values
  frontend/common/src/constants/localizedConstants.tsx
  frontend/talentsearch/src/js/api/userOperations.graphql
  frontend/talentsearch/src/js/components/Router.tsx
  frontend/talentsearch/src/js/components/profile/ProfilePage/ProfilePage.stories.tsx
  frontend/talentsearch/src/js/components/profile/ProfilePage/ProfilePage.tsx
Labels: PR:minor

#2418 fix: search pools render condition
  frontend/talentsearch/src/js/components/search/SearchContainer.tsx
Labels: PR:trivial

#2413 1914 About Me Edit Form
  frontend/common/src/constants/localizedConstants.tsx
  frontend/package-lock.json
  frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.stories.tsx
  frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.test.tsx
  frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.tsx
  frontend/talentsearch/src/js/components/aboutMeForm/aboutMeFormOperations.graphql
Labels: PR:minor

#2429 Move legend to be direct descendant of fieldset
  frontend/common/src/components/inputPartials/Fieldset/Fieldset.tsx
Labels: PR:trivial

#2432 Make bounded box contents clickable
  frontend/common/src/components/form/Checkbox/Checkbox.tsx
Labels: PR:trivial

#2442 Bug/2410 fix lh a11y issues
  frontend/common/hydrogen.config.json
  frontend/common/src/components/Footer/Footer.tsx
  frontend/common/src/components/form/MultiSelect/MultiSelect.tsx
Labels: PR:minor

#2444 Bugfix - Multiselect width
  frontend/common/src/components/form/MultiSelect/MultiSelect.stories.tsx
  frontend/common/src/components/form/MultiSelect/MultiSelect.tsx
Labels: bug, PR:trivial

#2450 Ignore dependabot PRs from the Chromatic storybook workflow
  .github/workflows/storybook.yml
Labels: tooling

#2326 1921 - Work Location Preference form
  frontend/common/src/components/form/Checklist/Checklist.tsx
  frontend/common/src/components/inputPartials/InputLabel/InputLabel.tsx
  frontend/common/src/components/inputPartials/InputWrapper/InputWrapper.tsx
  frontend/common/src/constants/localizedConstants.tsx
  frontend/talentsearch/src/js/applicantProfileRoutes.ts
  frontend/talentsearch/src/js/components/Router.tsx
  frontend/talentsearch/src/js/components/workLocationPreferenceForm/WorkLocationPreferenceForm.stories.tsx
  frontend/talentsearch/src/js/components/workLocationPreferenceForm/WorkLocationPreferenceForm.test.tsx
  frontend/talentsearch/src/js/components/workLocationPreferenceForm/WorkLocationPreferenceForm.tsx
  frontend/talentsearch/src/js/components/workLocationPreferenceForm/workLocationPreferenceOperations.graphql
Labels: PR:minor

#2357 Add mutations for experiences
  api/app/Models/AwardExperience.php
  api/app/Models/CommunityExperience.php
  api/app/Models/EducationExperience.php
  api/app/Models/ExperienceSkill.php
  api/app/Models/PersonalExperience.php
  api/app/Models/Skill.php
  api/app/Models/WorkExperience.php
  api/app/Policies/ExperiencePolicy.php
  api/app/Providers/AuthServiceProvider.php
  api/database/factories/AwardExperienceFactory.php
  api/database/factories/CommunityExperienceFactory.php
  api/database/factories/EducationExperienceFactory.php
  api/database/factories/ExperienceSkillFactory.php
  api/database/factories/PersonalExperienceFactory.php
  api/database/factories/WorkExperienceFactory.php
  api/database/seeders/DatabaseSeeder.php
  api/graphql/schema.graphql
  api/storage/app/lighthouse-schema.graphql
  frontend/common/src/fakeData/fakeExperienceSkills.ts
  frontend/common/src/fakeData/fakeExperiences.ts
  frontend/talentsearch/src/js/api/applicantOperations.graphql
  frontend/talentsearch/src/js/components/ExperienceAccordion/ExperienceAccordion.stories.tsx
  frontend/talentsearch/src/js/components/ExperienceAccordion/individualExperienceAccordions/AwardAccordion.tsx
  frontend/talentsearch/src/js/components/ExperienceAccordion/individualExperienceAccordions/CommunityAccordion.tsx
  frontend/talentsearch/src/js/components/ExperienceAccordion/individualExperienceAccordions/EducationAccordion.tsx
  frontend/talentsearch/src/js/components/ExperienceAccordion/individualExperienceAccordions/PersonalAccordion.tsx
  frontend/talentsearch/src/js/components/ExperienceAccordion/individualExperienceAccordions/WorkAccordion.tsx
  frontend/talentsearch/src/js/components/applicantProfile/ExperienceAndSkills.stories.tsx
  frontend/talentsearch/src/js/components/applicantProfile/ExperienceAndSkills.tsx
  frontend/talentsearch/src/js/components/skills/SkillAccordion/SkillAccordion.stories.tsx
  frontend/talentsearch/src/js/components/skills/SkillAccordion/SkillAccordion.test.tsx
  frontend/talentsearch/src/js/components/skills/SkillAccordion/SkillAccordion.tsx
Labels: PR:minor

#2430 Fix admin docker env
  frontend/admin/.apache_env
  frontend/admin/.env.example
  infrastructure/docker-compose.yml
Labels: PR:trivial

#2431 2423 buttons wrapped by links
  frontend/admin/src/js/components/classification/ClassificationPage.tsx
  frontend/admin/src/js/components/cmoAsset/CmoAssetPage.tsx
  frontend/admin/src/js/components/dashboard/Dashboard.tsx
  frontend/admin/src/js/components/department/DepartmentPage.tsx
  frontend/admin/src/js/components/pool/PoolPage.tsx
  frontend/admin/src/js/components/poolCandidate/PoolCandidatePage.tsx
  frontend/admin/src/js/components/skill/SkillPage.tsx
  frontend/admin/src/js/components/skillFamily/SkillFamilyPage.tsx
  frontend/admin/src/js/components/user/UserPage.tsx
  frontend/common/src/components/Button/Button.tsx
  frontend/common/src/components/Link/Link.stories.tsx
  frontend/common/src/components/Link/Link.tsx
  frontend/talentsearch/src/js/components/applicantProfile/CancelButton.tsx
Labels: PR:trivial

#2422 Fix routing fallback location
  frontend/admin/src/.htaccess
  frontend/talentsearch/src/.htaccess
Labels: PR:trivial

#2424 Talent Search - Pluralize Candidate Result Count #2370
  frontend/talentsearch/src/js/components/search/EstimatedCandidates.tsx
Labels: PR:trivial

#2446 Migrate faker.js to @faker-js/faker
  frontend/common/package.json
  frontend/common/src/fakeData/fakeClassifications.ts
  frontend/common/src/fakeData/fakeCmoAssets.ts
  frontend/common/src/fakeData/fakeDepartments.ts
  frontend/common/src/fakeData/fakeExperienceSkills.ts
  frontend/common/src/fakeData/fakeExperiences.ts
  frontend/common/src/fakeData/fakePoolCandidateFilters.ts
  frontend/common/src/fakeData/fakePoolCandidates.ts
  frontend/common/src/fakeData/fakePools.ts
  frontend/common/src/fakeData/fakeSearchRequests.ts
  frontend/common/src/fakeData/fakeSkillFamilies.ts
  frontend/common/src/fakeData/fakeSkills.ts
  frontend/common/src/fakeData/fakeUsers.ts
  frontend/package-lock.json
Labels: PR:trivial

#2447 Bug: 2358 - Fix Missing Breadcrumb Key
  frontend/common/src/components/Breadcrumbs/Breadcrumbs.tsx
Labels: PR:trivial

#2449 Switch Label to string or element and tweaks wherever
  frontend/common/src/components/form/Checkbox/Checkbox.stories.tsx
  frontend/common/src/components/form/Checkbox/Checkbox.tsx
  frontend/common/src/components/form/Checklist/Checklist.stories.tsx
  frontend/common/src/components/form/Input/Input.stories.tsx
  frontend/common/src/components/form/Input/Input.tsx
  frontend/common/src/components/form/Radio/Radio.stories.tsx
  frontend/common/src/components/form/Radio/Radio.tsx
  frontend/common/src/components/form/RadioGroup/RadioGroup.stories.tsx
  frontend/common/src/components/form/RadioGroup/RadioGroup.tsx
  frontend/common/src/components/form/Select/Select.stories.tsx
  frontend/common/src/components/form/Select/Select.tsx
  frontend/common/src/components/form/TextArea/TextArea.stories.tsx
  frontend/common/src/components/form/TextArea/TextArea.tsx
  frontend/common/src/constants/localizedConstants.tsx
  frontend/talentsearch/src/js/components/workPreferencesForm/WorkPreferencesForm.tsx
Labels: PR:trivial

#2478 Remove Required tag from some User & PoolCandidate fields
  frontend/admin/src/js/components/poolCandidate/CreatePoolCandidate.tsx
  frontend/admin/src/js/components/poolCandidate/UpdatePoolCandidate.tsx
  frontend/admin/src/js/components/user/CreateUser.tsx
  frontend/admin/src/js/components/user/UpdateUser.tsx
Labels: PR:emergency

#2461 Language information form
  frontend/talentsearch/src/js/components/Router.tsx
  frontend/talentsearch/src/js/components/languageInformationForm/LanguageInformationForm.stories.tsx
  frontend/talentsearch/src/js/components/languageInformationForm/LanguageInformationForm.test.tsx
  frontend/talentsearch/src/js/components/languageInformationForm/LanguageInformationForm.tsx
  frontend/talentsearch/src/js/components/languageInformationForm/LanguageInformationOperations.graphql
Labels: PR:minor

#2323 1919 Government Information Form
  .editorconfig
  frontend/talentsearch/src/js/components/GovernmentInfoForm/GovInfoFormOperations.graphql
  frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.stories.tsx
  frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.test.tsx
  frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.tsx
  frontend/talentsearch/src/js/components/Router.tsx
  frontend/talentsearch/src/js/talentSearchRoutes.ts
Labels: PR:minor

#2480 1796 - Experience Form
  .bundlewatch.config.js
  frontend/talentsearch/src/js/components/Router.tsx
  frontend/talentsearch/src/js/components/awardDetailsForm/AwardDetailsForm.tsx
  frontend/talentsearch/src/js/components/educationExperienceForm/EducationExperienceForm.tsx
  frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.stories.tsx
  frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.test.tsx
  frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.tsx
  frontend/talentsearch/src/js/components/experienceForm/ExperienceSkills.tsx
  frontend/talentsearch/src/js/components/experienceForm/WatchFormValues.tsx
  frontend/talentsearch/src/js/components/experienceForm/defaultValues.ts
  frontend/talentsearch/src/js/components/experienceForm/experienceFormOperations.graphql
  frontend/talentsearch/src/js/components/experienceForm/mutations.ts
  frontend/talentsearch/src/js/components/experienceForm/submissionData.ts
  frontend/talentsearch/src/js/components/experienceForm/types.ts
  frontend/talentsearch/src/js/components/personalExperienceForm/PersonalExperienceForm.tsx
  frontend/talentsearch/src/js/components/skills/AddSkillsToExperience/AddSkillsToExperience.tsx
  frontend/talentsearch/src/js/components/skills/SearchBar/SearchBar.tsx
  frontend/talentsearch/src/js/components/skills/SkillResults/SkillResults.tsx
  frontend/talentsearch/src/js/components/skills/SkillsInDetail/SkillsInDetail.tsx
  frontend/talentsearch/src/js/components/workExperienceForm/WorkExperienceForm.tsx
Labels: PR:major

#2528 A11y - 2427 document landmarks
  frontend/admin/src/js/components/dashboard/Dashboard.tsx
  frontend/talentsearch/src/js/components/PageContainer.tsx
Labels: PR:minor

#2531 Fix bug with candidate ID in requests component directory
  frontend/admin/src/js/components/searchRequest/SingleSearchRequest.tsx
  frontend/admin/src/js/components/searchRequest/SingleSearchRequestTable.tsx
  frontend/admin/src/js/components/searchRequest/UpdateSearchRequest.tsx
Labels: PR:trivial

#2525 Fix node in maintenance container
  .github/workflows/check-lighthouse-schema.yml
  auth/package.json
  frontend/package-lock.json
  infrastructure/docker-compose.ci.yml
  infrastructure/docker-compose.yml
  infrastructure/maintenance-container/Dockerfile
  maintenance/scripts/lib/load_nvm.sh
  maintenance/scripts/refresh_admin.sh
  maintenance/scripts/refresh_auth.sh
  maintenance/scripts/refresh_common.sh
  maintenance/scripts/refresh_indigenousapprenticeship.sh
  maintenance/scripts/refresh_talentsearch.sh
  maintenance/scripts/setup.sh
Labels: PR:trivial

#2537 linting in frontend - prettier
  frontend/admin/src/js/components/menu/SideMenu.tsx
  frontend/admin/src/js/components/poolCandidate/CreatePoolCandidate.tsx
  frontend/admin/src/js/components/poolCandidate/UpdatePoolCandidate.tsx
  frontend/admin/src/js/components/searchRequest/SingleSearchRequest.tsx
  frontend/admin/src/js/components/searchRequest/SingleSearchRequestTable.tsx
  frontend/admin/src/js/components/searchRequest/UpdateSearchRequest.tsx
  frontend/admin/src/js/components/skillFamily/SkillFamilyTable.tsx
  frontend/common/src/components/SearchRequestFilters/SearchRequestFilters.tsx
  frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.tsx
  frontend/talentsearch/src/js/components/skills/AddSkillsToExperience/AddSkillsToExperience.tsx
  frontend/talentsearch/src/js/components/skills/AddedSkills/AddedSkills.tsx
Labels: PR:trivial

#2527 Linting - @typescript-eslint/no-unused-vars #2489
  frontend/admin/src/js/components/ClientProvider.tsx
  frontend/admin/src/js/components/classification/CreateClassification.tsx
  frontend/admin/src/js/components/classification/UpdateClassification.tsx
  frontend/admin/src/js/components/cmoAsset/CreateCmoAsset.tsx
  frontend/admin/src/js/components/poolCandidate/UpdatePoolCandidate.tsx
  frontend/admin/src/js/types/react-table-config.d.ts
  frontend/common/src/components/Footer/Footer.tsx
  frontend/common/src/components/Link/Link.stories.tsx
  frontend/common/src/components/form/BasicForm.tsx
  frontend/common/src/helpers/router.tsx
  frontend/common/src/types/utilityTypes.ts
  frontend/indigenousapprenticeship/src/js/components/HelloWorld/HelloWorld.test.tsx
  frontend/indigenousapprenticeship/src/js/components/HelloWorld/HelloWorld.tsx
  frontend/talentsearch/src/js/components/applicantProfile/SaveButton.tsx
  frontend/talentsearch/src/js/components/search/SearchPage.tsx
  frontend/talentsearch/src/js/types/react-table-config.d.ts
  frontend/talentsearch/src/js/types/utilityTypes.ts
Labels: PR:trivial

#2535 Font weight 100 too light on Firefox Linux #2441
  frontend/admin/src/js/components/dashboard/Dashboard.tsx
  frontend/talentsearch/src/js/components/applicantProfile/ProfileFormWrapper.tsx
  frontend/talentsearch/src/js/components/search/SearchPools.tsx
Labels: PR:trivial

#2414 Add package integrity check
  .github/workflows/package-integrity-check.yml
  frontend/common/package.json
  frontend/common/src/tooling/checkIntegrity.js
  frontend/common/src/tooling/checkIntegrity.test.js
  frontend/common/src/tooling/checkIntegrityLib.js
  frontend/package-lock.json
  frontend/talentsearch/package.json
Labels: PR:trivial

#2538 Added smoke tests for setup scripts and docker environment
  .github/workflows/docker-smoke-test.yml
Labels: PR:trivial

#2500 logout bug in local environment
  frontend/admin/src/.htaccess
  frontend/admin/src/config.sjs
  frontend/admin/src/js/adminConstants.ts
Labels: PR:trivial

#2481 Fix language search filtering out bilingual
  api/app/Models/PoolCandidate.php
  api/database/factories/PoolCandidateFactory.php
  api/database/factories/PoolCandidateFilterFactory.php
  api/database/factories/PoolFactory.php
  api/database/factories/UserFactory.php
  api/database/helpers/ApiEnums.php
  api/graphql/schema.graphql
  api/tests/Feature/PoolCandidateTest.php
  frontend/common/src/constants/localizedConstants.tsx
  frontend/talentsearch/src/js/components/search/SearchForm.tsx
Labels: PR:trivial

#2569 linting - type any
  frontend/admin/src/js/adminConstants.ts
  frontend/admin/src/js/components/GlobalFilter.tsx
  frontend/admin/src/js/types/react-table-config.d.ts
  frontend/common/src/components/form/BasicForm.tsx
  frontend/common/src/types/utilityTypes.ts
  frontend/talentsearch/src/js/components/search/SearchContainer.tsx
  frontend/talentsearch/src/js/types/react-table-config.d.ts
  frontend/talentsearch/src/js/types/utilityTypes.ts
Labels: PR:trivial

#2561 Feature - Common Dialog Component
  frontend/common/package.json
  frontend/common/src/components/Dialog/Content.tsx
  frontend/common/src/components/Dialog/Dialog.stories.tsx
  frontend/common/src/components/Dialog/Dialog.test.tsx
  frontend/common/src/components/Dialog/Dialog.tsx
  frontend/common/src/components/Dialog/Overlay.tsx
  frontend/common/src/components/Dialog/dialog.css
  frontend/common/src/components/Dialog/index.ts
  frontend/common/src/fakeData/fakeExperienceSkills.ts
  frontend/package-lock.json
Labels: PR:major

#2582 Fix exhaustive deps linting errors
  frontend/admin/.eslintrc
  frontend/admin/src/js/components/dashboard/Dashboard.tsx
  frontend/admin/src/js/components/searchRequest/SearchRequestTable.tsx
  frontend/common/src/helpers/router.tsx
  frontend/common/src/hooks/useDeepCompareEffect.ts
  frontend/indigenousapprenticeship/.eslintrc
  frontend/indigenousapprenticeship/src/js/components/PageContainer.tsx
  frontend/talentsearch/.eslintrc
  frontend/talentsearch/src/js/components/PageContainer.tsx
  frontend/talentsearch/src/js/components/search/SearchForm.tsx
Labels: PR:trivial

#2581 Bug - 2577 - fix classification not being removed when student
  api/graphql/schema.graphql
  api/storage/app/lighthouse-schema.graphql
  frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.tsx
Labels: PR:trivial
