Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2022-06, with the labels that each got.

#2719 Add e2e tests and commands for auth flows on devel
  .github/workflows/e2e-tests.yml
  .gitignore
  README.md
  api/config/session.php
  docker-compose.yml
  frontend/cypress.json
  frontend/cypress/README.md
  frontend/cypress/fixtures/users.json
  frontend/cypress/integration/admin/auth.spec.js
  frontend/cypress/integration/talentsearch/footer.spec.js
  frontend/cypress/integration/talentsearch/language-selection.spec.js
  frontend/cypress/integration/talentsearch/static-pages.spec.js
  frontend/cypress/reporters-config.json
  frontend/cypress/support/commands.js
  frontend/cypress/support/graphql-test-utils.js
  frontend/cypress/support/index.js
  frontend/package-lock.json
  frontend/package.json
  infrastructure/conf/mock-oauth2-server.json
Labels: tooling

#2949 Accessibility Documentation
  .vscode/project-words.txt
  documentation/accessibility.md
Labels: documentation, accessibility

#2954 Added restart policy on mock-auth
  docker-compose.yml
Labels: bug, tooling, interruption

#3011 Feature - Create account page
  .vscode/project-words.txt
  frontend/common/hydrogen.config.json
  frontend/common/src/components/Alert/Alert.stories.tsx
  frontend/common/src/components/Alert/Alert.tsx
  frontend/common/src/components/Alert/index.ts
  frontend/common/src/components/index.ts
  frontend/common/src/constants/localizedConstants.tsx
  frontend/common/src/helpers/format.tsx
  frontend/talentsearch/src/js/applicantProfileRoutes.ts
  frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.stories.tsx
  frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.test.tsx
  frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.tsx
  frontend/talentsearch/src/js/components/Router.tsx
  frontend/talentsearch/src/js/components/createAccount/CreateAccountPage.test.tsx
  frontend/talentsearch/src/js/components/createAccount/CreateAccountPage.tsx
  frontend/talentsearch/src/js/components/createAccount/createAccountOperations.graphql
Labels: feature

#3021 Enable snazzy adminer theme
  docker-compose.yml
  infrastructure/adminer-hydra-theme.css
Labels: tooling, interruption

#3066 Speed up phpunit test runs
  api/tests/Feature/AuthServiceProviderTest.php
  api/tests/Feature/PoolCandidateTest.php
  api/tests/Feature/UserTest.php
Labels: tooling, interruption
