Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2022-05, with the labels that each got.

#2575 linting - jsx a11y errors
  frontend/admin/.eslintrc
  frontend/admin/src/js/components/Table.tsx
  frontend/common/.eslintrc
  frontend/common/src/components/form/Checkbox/Checkbox.tsx
  frontend/common/src/components/inputPartials/Fieldset/Fieldset.stories.tsx
  frontend/indigenousapprenticeship/.eslintrc
  frontend/talentsearch/.eslintrc
  frontend/talentsearch/src/js/components/skills/SkillChecklist/SkillChecklist.tsx
Labels: PR:trivial

#2583 experience forms touch-ups
  frontend/talentsearch/src/js/components/communityExperienceForm/CommunityExperienceForm.tsx
  frontend/talentsearch/src/js/components/educationExperienceForm/EducationExperienceForm.tsx
  frontend/talentsearch/src/js/components/personalExperienceForm/PersonalExperienceForm.tsx
  frontend/talentsearch/src/js/components/workExperienceForm/WorkExperienceForm.tsx
Labels: PR:trivial

#2586 1994 ensure routing is working for all profile edit forms
  frontend/talentsearch/src/js/applicantProfileRoutes.ts
  frontend/talentsearch/src/js/components/Router.tsx
  frontend/talentsearch/src/js/components/applicantProfile/ExperienceAndSkills.tsx
  frontend/talentsearch/src/js/components/diversityEquityInclusion/DiversityEquityInclusionForm.tsx
  frontend/talentsearch/src/js/components/profile/ProfilePage/ProfilePage.tsx
Labels: PR:trivial

#2620 2573 - Improve search spinner a11y
  frontend/talentsearch/src/js/components/Spinner/Spinner.stories.tsx
  frontend/talentsearch/src/js/components/Spinner/Spinner.tsx
  frontend/talentsearch/src/js/components/Spinner/index.ts
  frontend/talentsearch/src/js/components/search/EstimatedCandidates.tsx
  frontend/talentsearch/src/js/components/search/SearchContainer.tsx
Labels: PR:trivial

#2674 Upgrade to Jest 28
  frontend/admin/package.json
  frontend/common/package.json
  frontend/indigenousapprenticeship/package.json
  frontend/package-lock.json
  frontend/talentsearch/package.json
Labels: PR:trivial

#2740 IAP Homepage Copy Updates
  frontend/indigenousapprenticeship/src/js/components/Dialog/LearnDialog.tsx
  frontend/indigenousapprenticeship/src/js/components/Dialog/RequirementDialog.tsx
  frontend/indigenousapprenticeship/src/js/components/Home/Home.tsx
Labels: interruption, copy

#2779 Bug - 2777 - Check refreshed AuthState before returning
  frontend/common/src/components/ClientProvider/ClientProvider.tsx
Labels: e2e-candidate

#2649 Add a template for creating new issues
  .github/issue_template.yml
Labels: tooling, interruption

#2876 Rollback storybook 6.5
  frontend/admin/package.json
  frontend/common/package.json
  frontend/indigenousapprenticeship/package.json
  frontend/package-lock.json
  frontend/talentsearch/package.json
Labels: interruption

#2881 Fix gitignore permissions so they're stable
  api/storage/app/.gitignore
  api/storage/app/public/.gitignore
  api/storage/framework/.gitignore
  api/storage/framework/cache/data/.gitignore
  api/storage/framework/testing/.gitignore
Labels: tooling

#2889 Fixed phpunit tests for DataSet
  api/app/Services/Contracts/DatasetInterface.php
  api/tests/Feature/AuthServiceProviderTest.php
Labels: bug, tests, interruption

#2886 Enable AUTH_DEFAULT_USER by default for local dev
  api/.env.example
Labels: tooling, interruption

#2888 hack: get FR iap story working for preview
  frontend/indigenousapprenticeship/src/js/components/Home/Home.stories.tsx
Labels: bug, interruption

#2871 Finish migrating from email to sub for auth
  api/app/Providers/AuthServiceProvider.php
  api/graphql/schema.graphql
  api/storage/app/lighthouse-schema.graphql
  frontend/admin/src/js/components/user/CreateUser.tsx
  frontend/admin/src/js/components/user/UpdateUser.tsx
  frontend/common/src/helpers/util.ts
  frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.tsx
  frontend/talentsearch/src/js/components/aboutMeForm/aboutMeFormOperations.graphql
Labels: e2e-candidate
