Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2022-11, with the labels that each got.

#4520 Updates Hydrogen to beta.31 in preparation for theming
  frontend/admin/.storybook/main.js
  frontend/admin/package.json
  frontend/admin/webpack.base.js
  frontend/common/.storybook/main.js
  frontend/common/package.json
  frontend/common/src/components/Alert/Alert.tsx
  frontend/common/src/components/Alert/alert.css
  frontend/common/src/components/Button/Button.tsx
  frontend/common/src/components/Chip/chip.css
  frontend/common/src/components/Footer/Footer.tsx
  frontend/common/src/components/Header/Header.tsx
  frontend/common/src/components/MissingSkills/MissingSkills.tsx
  frontend/common/src/components/Pill/Pill.tsx
  frontend/common/src/components/Separator/Separator.tsx
  frontend/common/src/components/SideMenu/SideMenuItem.tsx
  frontend/common/src/components/Tabs/tabs.css
  frontend/common/src/components/ToggleGroup/toggle-group.css
  frontend/common/src/components/inputPartials/InputContext/InputContext.tsx
  frontend/common/src/components/inputPartials/InputError/InputError.tsx
  frontend/hydrogen.config.json
  frontend/indigenousapprenticeship/.storybook/main.js
  frontend/indigenousapprenticeship/package.json
  frontend/indigenousapprenticeship/webpack.base.js
  frontend/package-lock.json
  frontend/talentsearch/.storybook/main.js
  frontend/talentsearch/package.json
  frontend/talentsearch/src/js/components/Browse/BrowsePoolsPage.tsx
  frontend/talentsearch/src/js/components/Browse/PoolCard/pool-card.css
  frontend/talentsearch/src/js/components/myStatusForm/MyStatusForm.tsx
  frontend/talentsearch/src/js/components/support/SupportPage.tsx
  frontend/talentsearch/webpack.base.js
Labels: dependencies, design

#4585 Updates Hydrogen to 2.0.0-beta.33
  frontend/admin/package.json
  frontend/common/package.json
  frontend/hydrogen.config.json
  frontend/indigenousapprenticeship/package.json
  frontend/package-lock.json
  frontend/talentsearch/package.json
Labels: bug, dependencies

#4859 Feature - 4796 - Add language dropdown for IAP
  frontend/indigenousapprenticeship/src/js/components/Home/Home.test.tsx
  frontend/indigenousapprenticeship/src/js/components/Home/Home.tsx
  frontend/indigenousapprenticeship/src/js/components/LanguageSelector/LanguageSelector.tsx
  frontend/indigenousapprenticeship/src/js/components/Layout.tsx
  frontend/indigenousapprenticeship/src/js/lang/fr.json
Labels: blocked
