Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2022-07, with the labels that each got.

#3199 Ensure field height is consistent both with/without context info
  frontend/common/src/css/common.css
Labels: design, interruption

#3084 Cypress Workflow Tests
  .vscode/project-words.txt
  api/database/seeders/UserSeederLocal.php
  frontend/.prettierrc
  frontend/common/.prettierrc
  frontend/cypress/integration/admin/admin-workflows.spec.js
  frontend/cypress/integration/admin/auth.spec.js
  frontend/cypress/integration/talentsearch/profile-workflows.spec.js
  frontend/cypress/integration/talentsearch/search-page.spec.js
  frontend/cypress/integration/talentsearch/search-workflows.spec.js
  frontend/cypress/integration/talentsearch/searchpage.spec.js
  frontend/cypress/support/commands.js
  frontend/cypress/support/graphql-test-utils.js
  frontend/indigenousapprenticeship/.prettierrc
  frontend/package-lock.json
  frontend/package.json
  frontend/talentsearch/.prettierrc
Labels: blocked

#3288 Tooling - Add jest-axe
  frontend/admin/jest.config.js
  frontend/admin/package.json
  frontend/admin/src/js/tests/setup.ts
  frontend/common/jest.config.js
  frontend/common/package.json
  frontend/common/src/components/Pagination/Pagination.tsx
  frontend/common/src/components/accordion/Accordion.test.tsx
  frontend/common/src/components/inputPartials/Fieldset/Fieldset.tsx
  frontend/common/src/tests/.gitkeep
  frontend/common/src/tests/setup.ts
  frontend/common/tests/setup.js
  frontend/indigenousapprenticeship/jest.config.js
  frontend/indigenousapprenticeship/package.json
  frontend/indigenousapprenticeship/src/js/components/Card/Card.tsx
  frontend/indigenousapprenticeship/src/js/components/Home/Home.test.tsx
  frontend/indigenousapprenticeship/src/js/components/Step/Step.tsx
  frontend/indigenousapprenticeship/src/js/tests/setup.ts
  frontend/package-lock.json
  frontend/talentsearch/jest.config.js
  frontend/talentsearch/package.json
  frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.test.tsx
  frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.test.tsx
  frontend/talentsearch/src/js/components/createAccount/CreateAccountPage.test.tsx
  frontend/talentsearch/src/js/components/diversityEquityInclusion/DiversityEquityInclusionForm.test.tsx
  frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.test.tsx
  frontend/talentsearch/src/js/components/languageInformationForm/LanguageInformationForm.test.tsx
  frontend/talentsearch/src/js/components/myStatusForm/MyStatusForm.test.tsx
  frontend/talentsearch/src/js/components/search/SearchContainer.test.tsx
  frontend/talentsearch/src/js/components/skills/AddedSkills/AddedSkills.test.tsx
  frontend/talentsearch/src/js/components/skills/SkillChecklist/SkillChecklist.test.tsx
  frontend/talentsearch/src/js/components/skills/SkillResults/SkillResults.test.tsx
  frontend/talentsearch/src/js/components/workLocationPreferenceForm/WorkLocationPreferenceForm.test.tsx
  frontend/talentsearch/src/js/tests/setup.ts
  frontend/talentsearch/src/js/tests/testUtils.tsx
Labels: accessibility

#3362 Improve first-time setup experience via doc update
  maintenance/README.md
Labels: documentation

#3427 Add Cell Key to Latest Requests Table
  frontend/admin/src/js/components/dashboard/LatestRequestsTable.tsx
Labels: bug, interruption

#3436 Add run-script for building the merged storybook
  frontend/package.json
Labels: tooling, interruption

#3450 add action status badges
  README.md
Labels: interruption

#3522 Removed gitignore from when we were merging mock-auth
  .gitignore
Labels: debt, interruption

#3528 navigate redirect to /profile
  api/.env.example
Labels: deployment

#3539 Allow chromatic to run on every commit on main branch
  .github/workflows/storybook.yml
Labels: tooling
