Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2023-01, with the labels that each got.

#5384 Fixes whitespace inconsistencies on the Job Poster UI
  apps/web/src/pages/PoolAdvertisementPage/PoolAdvertisementPage.tsx
  frontend/common/src/components/Card/Card.tsx
Labels: debt

#5506 Hydrogen 2.0.0-beta.39
  .vscode/hydrogen.code-snippets
  apps/web/package.json
  apps/web/src/pages/SearchPage/EstimatedCandidates.tsx
  frontend/admin/package.json
  frontend/common/package.json
  frontend/common/src/components/Accordion/Accordion.tsx
  frontend/common/src/components/Alert/Alert.tsx
  frontend/common/src/components/Button/Button.tsx
  frontend/common/src/components/CardLink/CardLink.tsx
  frontend/common/src/components/ScrollArea/ScrollArea.tsx
  frontend/common/src/components/Switch/Switch.tsx
  frontend/common/src/components/Tabs/Tabs.tsx
  frontend/common/src/components/TileLink/TileLink.tsx
  frontend/common/src/components/Toast/Toast.tsx
  package-lock.json
  package.json
Labels: bug, dependencies

#5531 Tooling/5513 dcm seeding team
  api/database/seeders/DatabaseSeeder.php
  api/database/seeders/ProdSeeder.php
  api/database/seeders/TeamSeeder.php
  api/database/seeders/UatSeeder.php
Labels: deployment
