Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2023-10, with the labels that each got.

#8111 Updates Hydrogen to 2.0.3
  apps/web/package.json
  package-lock.json
  package.json
Labels: dependencies

#8172 Fixes the styling of the job cards
  apps/web/src/components/PoolCard/IconLabel.tsx
  apps/web/src/components/PoolCard/PoolCard.tsx
  apps/web/src/components/PoolCard/pool-card.css
Labels: debt, interruption, styling

#8168 [Copy] Updates skill showcase copy
  apps/web/src/lang/fr.json
  apps/web/src/pages/Skills/SkillShowcasePage.tsx
Labels: blocked: copy

#8179 [Feature] Skill library showcase content
  apps/web/src/lang/fr.json
  apps/web/src/pages/Skills/SkillLibraryPage.tsx
Labels: blocked: copy

#8177 [Copy] Update skill library table
  apps/web/src/components/SkillDialog/utils.ts
  apps/web/src/components/Table/ResponsiveTable/ResponsiveTable.tsx
  apps/web/src/lang/fr.json
  apps/web/src/pages/Skills/components/SkillLibraryTable.tsx
Labels: blocked: copy

#7946 Updates hydrogen.config and preps alerts, buttons, links, and standard cards for dark mode
  apps/web/src/components/Hero/Hero.tsx
  apps/web/src/components/HeroCard/HeroCard.tsx
  apps/web/src/components/SearchRequestTable/components/SearchRequestsTableFilterDialog.tsx
  apps/web/src/components/StatusItem/StatusItem.tsx
  apps/web/src/components/Table/ResponsiveTable/SortButton.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/EducationRequirementsSection.tsx
  apps/web/src/pages/ProfileAndApplicationsPage/components/ProfileAndApplicationsHeading.tsx
  apps/web/src/pages/SearchRequests/RequestConfirmationPage/RequestConfirmationPage.tsx
  apps/web/src/pages/SearchRequests/SearchPage/components/EstimatedCandidates.tsx
  apps/web/src/pages/Users/IndexUserPage/components/UserTableFilterDialog/UserTableFilterDialog.tsx
  hydrogen.config.json
  packages/forms/src/components/ErrorSummary.tsx
  packages/forms/src/components/Repeater/Repeater.tsx
  packages/forms/src/components/UnsavedChanges.tsx
  packages/storybook-helpers/decorators/ThemeDecorator.tsx
  packages/theme/src/components/ThemeProvider.tsx
  packages/ui/src/components/Alert/Alert.stories.tsx
  packages/ui/src/components/Alert/Alert.tsx
  packages/ui/src/components/Alert/utils.ts
  packages/ui/src/components/Button/Button.stories.tsx
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/Button/Counter.tsx
  packages/ui/src/components/ButtonLinkContent/ButtonLinkContent.tsx
  packages/ui/src/components/Card/Card.stories.tsx
  packages/ui/src/components/Card/Card.tsx
  packages/ui/src/components/Card/CardFlat/CardFlat.stories.tsx
  packages/ui/src/components/Card/CardFlat/CardFlat.tsx
  packages/ui/src/components/CardLink/CardLink.stories.tsx
  packages/ui/src/components/CardLink/CardLink.tsx
  packages/ui/src/components/Link/DownloadCsv.stories.tsx
  packages/ui/src/components/Link/DownloadCsv.tsx
  packages/ui/src/components/Link/Link.stories.tsx
  packages/ui/src/components/Link/Link.tsx
  packages/ui/src/components/Link/ScrollToLink.tsx
  packages/ui/src/components/Styleguide/Styleguide.stories.tsx
  packages/ui/src/components/Styleguide/Styleguide.tsx
  packages/ui/src/components/Styleguide/index.ts
  packages/ui/src/components/TableOfContents/AnchorLink.tsx
  packages/ui/src/components/TableOfContents/Navigation.tsx
  packages/ui/src/hooks/useCommonButtonLinkStyles.ts
  packages/ui/src/types.ts
  packages/ui/src/utils/button/getButtonBackgroundColor.ts
  packages/ui/src/utils/button/getButtonBaseStyle.ts
  packages/ui/src/utils/button/getButtonBorderColor.ts
  packages/ui/src/utils/button/getButtonDisplay.ts
  packages/ui/src/utils/button/getButtonFontColor.ts
  packages/ui/src/utils/button/getButtonFontWeight.ts
  packages/ui/src/utils/button/getButtonShadow.ts
  packages/ui/src/utils/button/getButtonStyles.ts
Labels: feature, accessibility, styling

#8292 [Feature] Executive teaser
  apps/web/.env.example
  apps/web/public/config.ejs
  apps/web/src/components/CallToActionCard/CallToActionCard.stories.tsx
  apps/web/src/components/CallToActionCard/CallToActionCard.tsx
  apps/web/src/lang/fr.json
  apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.tsx
  packages/env/src/utils.ts
Labels: blocked: copy
