Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2023-05, with the labels that each got.

#6524 [Styling] Updates line-height, fixes hero text size, fixes accordion whitespace
  apps/web/src/components/CallToAction/IconWrapper.tsx
  apps/web/src/components/CallToAction/styles.ts
  apps/web/src/components/Hero/Hero.tsx
  apps/web/src/components/UserProfile/SkillAccordion/SkillAccordion.tsx
  apps/web/src/pages/Applications/ApplicationResumeAddPage/ApplicationResumeAddPage.tsx
  apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
  hydrogen.config.json
  packages/ui/src/components/Accordion/styles.ts
Labels: accessibility, styling

#6539 [Feature] Null state for tables
  apps/web/src/components/Table/ApiManagedTable/BasicTable.tsx
  apps/web/src/components/Table/ClientManagedTable/Table.tsx
  apps/web/src/components/Table/tableMessages.ts
  apps/web/src/lang/fr.json
Labels: blocked: copy

#6602 [Feature] Self declaration form in application revamp
  api/graphql/schema.graphql
  api/storage/app/lighthouse-schema.graphql
  apps/web/src/components/EmploymentEquity/dialogs/IndigenousDialog.tsx
  apps/web/src/components/Router.tsx
  apps/web/src/components/SelfDeclaration/SelfDeclarationForm.stories.tsx
  apps/web/src/components/SelfDeclaration/SelfDeclarationForm.tsx
  apps/web/src/components/SelfDeclaration/SignAndContinue.tsx
  apps/web/src/hooks/useRoutes.ts
  apps/web/src/lang/fr.json
  apps/web/src/pages/Applications/ApplicationContext.tsx
  apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/ApplicationSelfDeclarationPage.tsx
  apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/CommunityCheckbox.tsx
  apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/CommunityError.tsx
  apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/CommunityIcon.tsx
  apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/CommunitySelection.tsx
  apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/CommunityTabs.tsx
  apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/HelpLink.tsx
  apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/SelfDeclarationForm.stories.tsx
  apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/SelfDeclarationForm.test.tsx
  apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/utils.ts
  apps/web/src/pages/Applications/applicationOperations.graphql
  apps/web/src/pages/Applications/educationStep/educationStepInfo.tsx
  apps/web/src/pages/Applications/profileStep/profileStepInfo.tsx
  apps/web/src/pages/Applications/questionsStep/questionsStepInfo.tsx
  apps/web/src/pages/Applications/resumeStep/resumeStepInfo.tsx
  apps/web/src/pages/Applications/reviewStep/reviewStepInfo.tsx
  apps/web/src/pages/Applications/selfDeclarationStep/selfDeclarationStepInfo.tsx
  apps/web/src/pages/Applications/selfDeclarationStep/selfDeclarationStepValidation.tsx
  apps/web/src/pages/Applications/skillsStep/skillsStepInfo.tsx
  apps/web/src/pages/Applications/successStep/successStepInfo.tsx
  apps/web/src/utils/applicationUtils.ts
  apps/web/src/utils/indigenousDeclaration.ts
Labels: blocked: copy

#6541 Feature - 6070 - Application education requirements
  apps/web/src/lang/fr.json
  apps/web/src/pages/Applications/ApplicationEducationPage/ApplicationEducationPage.tsx
  apps/web/src/pages/Applications/ApplicationEducationPage/LinkResume.tsx
  apps/web/src/pages/Applications/ApplicationQuestionsIntroductionPage/ApplicationQuestionsIntroductionPage.tsx
  apps/web/src/pages/Applications/ApplicationResumeIntroductionPage/ApplicationResumeIntroductionPage.tsx
  apps/web/src/pages/Applications/ApplicationSkillsIntroductionPage/ApplicationSkillsIntroductionPage.tsx
  apps/web/src/pages/Applications/applicationOperations.graphql
  apps/web/src/pages/Applications/educationStep/educationStepInfo.tsx
  apps/web/src/pages/Applications/educationStep/educationStepValidation.tsx
  packages/forms/src/components/RadioGroup/RadioGroup.tsx
Labels: blocked: copy

#6651 [Debt] Removes work weekends from Operational Requirements
  api/app/Console/Commands/RemoveOperationalRequirement.php
  api/database/helpers/ApiEnums.php
  api/database/seeders/PoolSeederUat.php
  api/graphql/schema.graphql
  api/storage/app/lighthouse-schema.graphql
  packages/i18n/src/lang/fr.json
  packages/i18n/src/messages/localizedConstants.tsx
Labels: deployment
