Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2023-06, with the labels that each got.

#6810 [Debt] Removes `FEATURE_ONGOING_RECRUITMENTS` flag
  api/.env.example
  api/config/feature.php
  apps/web/.env.example
  apps/web/public/config.ejs
  apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.test.tsx
  apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.tsx
  packages/env/src/useFeatureFlags.ts
  packages/env/src/utils.ts
Labels: deployment

#7029 [Feature] Profile and applications page update
  apps/e2e/cypress/e2e/talentsearch/profile-page.cy.js
  apps/web/src/components/ProfileDocument/ProfileDocument.tsx
  apps/web/src/components/Redirects/TalentRedirect.tsx
  apps/web/src/components/Router.tsx
  apps/web/src/components/UserProfile/UserProfile.stories.tsx
  apps/web/src/components/UserProfile/UserProfile.tsx
  apps/web/src/components/UserProfile/constants.ts
  apps/web/src/hooks/useRoutes.ts
  apps/web/src/lang/fr.json
  apps/web/src/pages/Applications/ApplicantDashboardPage/ApplicantDashboardPage.tsx
  apps/web/src/pages/Applications/ApplicantDashboardPage/components/DashboardHeading.tsx
  apps/web/src/pages/Applications/ApplicantDashboardPage/components/TrackApplications/TrackApplications.tsx
  apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx
  apps/web/src/pages/Profile/ProfilePage/ProfilePage.tsx
  apps/web/src/pages/Profile/ResumeAndRecruitmentPage/ResumeAndRecruitmentPage.stories.tsx
  apps/web/src/pages/Profile/ResumeAndRecruitmentPage/ResumeAndRecruitmentPage.test.tsx
  apps/web/src/pages/Profile/ResumeAndRecruitmentPage/ResumeAndRecruitmentPage.tsx
  apps/web/src/pages/Profile/ResumeAndRecruitmentPage/components/AddExperienceDialog.tsx
  apps/web/src/pages/Profile/ResumeAndRecruitmentPage/components/QualifiedRecruitmentsSection.tsx
  apps/web/src/pages/Profile/ResumeAndRecruitmentPage/components/ResumeAndRecruitment.tsx
  apps/web/src/pages/Profile/ResumeAndRecruitmentPage/components/ResumeSection.tsx
  apps/web/src/pages/Profile/ResumeAndRecruitmentPage/constants.ts
  apps/web/src/pages/Profile/ResumeAndRecruitmentPage/resumeAndRecruitmentOperations.graphql
  apps/web/src/pages/Users/AdminUserProfilePage/AdminUserProfilePage.tsx
  packages/i18n/src/lang/fr.json
  packages/i18n/src/messages/navigationMessages.ts
Labels: blocked: copy

#7027 [Feature] Only show relevant asset skills for snapshot view
  apps/web/src/lang/fr.json
  apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx
  apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationStatusForm/AssetSkillsFiltered.tsx
  apps/web/src/utils/skillUtils.ts
Labels: blocked: copy

#7109 [Dep] Hydrogen 2.0.2
  apps/web/package.json
  hydrogen.config.json
  package-lock.json
  package.json
Labels: dependencies
