Repository GCTC-NTGC/gc-digital-talent, pull requests merged in 2024-02, with the labels that each got.

#9139 Visual updates to SearchResultCard
  apps/e2e/cypress/e2e/talentsearch/search-workflows.cy.ts
  apps/web/src/lang/fr.json
  apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx
  apps/web/src/pages/SearchRequests/SearchPage/components/SearchResultCard.tsx
Labels: blocked: copy

#9029 [Feature] update job ad creation form
  apps/e2e/cypress/e2e/admin/pools.cy.ts
  apps/web/src/components/EducationRequirements/EducationRequirements.tsx
  apps/web/src/components/Hero/AdminHero.tsx
  apps/web/src/components/SkillBrowser/utils.ts
  apps/web/src/components/StatusItem/StatusItem.tsx
  apps/web/src/components/ToggleForm/LabelledTrigger.tsx
  apps/web/src/components/ToggleForm/NullDisplay.tsx
  apps/web/src/hooks/useToggleSectionInfo.ts
  apps/web/src/lang/fr.json
  apps/web/src/messages/processMessages.ts
  apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/SkillsQuickSummary.tsx
  apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.test.tsx
  apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/AssetSkillsSection.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateDialog.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/Display.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/CoreRequirementsSection/CoreRequirementsSection.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/CoreRequirementsSection/Display.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/CoreRequirementsSection/utils.ts
  apps/web/src/pages/Pools/EditPoolPage/components/EducationRequirementsSection.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/EssentialSkillsSection.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/GeneralQuestions.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/Display.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/PoolNameSection.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/SkillTable.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/SpecialNoteSection/Display.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/SpecialNoteSection/SpecialNoteSection.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/WhatToExpectSection/Display.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/WhatToExpectSection/WhatToExpectSection.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/WorkTasksSection/Display.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/WorkTasksSection/WorkTasksSection.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/YourImpactSection/Display.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/YourImpactSection/YourImpactSection.tsx
  apps/web/src/pages/Pools/EditPoolPage/types.ts
  apps/web/src/pages/Pools/PoolLayout.tsx
  apps/web/src/types/pool.ts
  apps/web/src/validators/process/classification.ts
  apps/web/src/validators/process/closingDate.ts
  apps/web/src/validators/process/coreRequirements.ts
  infrastructure/conf/nginx-conf-local/default
  packages/i18n/src/lang/fr.json
  packages/i18n/src/messages/commonMessages.ts
Labels: blocked: copy

#9286 Updates hero images
  apps/web/src/assets/img/exec-hero-landscape.webp
  apps/web/src/assets/img/exec-hero-portrait.webp
  apps/web/src/assets/img/exec-hero-tablet-portrait.webp
  apps/web/src/assets/img/hero-1-landscape.webp
  apps/web/src/assets/img/hero-1-portrait.webp
  apps/web/src/assets/img/hero-1-tablet-portrait.webp
  apps/web/src/assets/img/hero-2-landscape.webp
  apps/web/src/assets/img/hero-2-portrait.webp
  apps/web/src/assets/img/hero-2-tablet-portrait.webp
  apps/web/src/assets/img/hero-3-landscape.webp
  apps/web/src/assets/img/hero-3-portrait.webp
  apps/web/src/assets/img/hero-3-tablet-portrait.webp
  apps/web/src/assets/img/hero-4-landscape.webp
  apps/web/src/assets/img/hero-4-portrait.webp
  apps/web/src/assets/img/hero-4-tablet-portrait.webp
  apps/web/src/assets/img/manager-hero-landscape.webp
  apps/web/src/assets/img/manager-hero-portrait.webp
  apps/web/src/assets/img/manager-hero-tablet-portrait.webp
  apps/web/src/assets/img/manager-hero.webp
  apps/web/src/assets/img/people-sitting-in-line-shaking-hands.webp
  apps/web/src/components/Hero/HomeHero.tsx
  apps/web/src/pages/Home/ExecutiveHomePage/ExecutiveHomePage.tsx
  apps/web/src/pages/Home/HomePage/components/Hero/Hero.tsx
  apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
Labels: interruption, styling

#9329 [Feature] Remove process information subpages from tabs
  apps/e2e/cypress/e2e/admin/pools.cy.ts
  apps/web/src/lang/fr.json
  apps/web/src/pages/Pools/PoolLayout.tsx
  apps/web/src/types/pool.ts
  apps/web/src/utils/poolUtils.tsx
Labels: blocked: copy

#9484 [Fix] Add missing permission to platform admin
  api/config/rolepermission.php
Labels: deployment

#9395 [Feature] Pool opportunity length field
  api/app/Enums/PoolOpportunityLength.php
  api/app/GraphQL/Validators/PoolIsCompleteValidator.php
  api/app/Models/Pool.php
  api/app/Providers/GraphQLServiceProvider.php
  api/database/factories/PoolFactory.php
  api/database/migrations/2024_02_16_182944_length_of_opportunity_column_pools_table.php
  api/graphql/schema.graphql
  api/storage/app/lighthouse-schema.graphql
  apps/e2e/cypress/e2e/admin/pools.cy.ts
  apps/e2e/cypress/e2e/talentsearch/submit-application-iap.cy.ts
  apps/e2e/cypress/support/poolHelpers.ts
  apps/playwright/fixtures/PoolPage.ts
  apps/playwright/tests/applicant/application.spec.ts
  apps/web/src/lang/fr.json
  apps/web/src/messages/processMessages.ts
  apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/Display.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/PoolNameSection.tsx
  apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/utils.ts
  apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
  apps/web/src/utils/poolUtils.tsx
  apps/web/src/validators/process/classification.ts
  packages/i18n/src/index.tsx
  packages/i18n/src/lang/fr.json
  packages/i18n/src/messages/localizedConstants.tsx
Labels: blocked: copy
